### ISSUE TITLE
Add Xfwm4 theme

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#1]
Thank you for this amazing work. Please make Windows-10-Acrylic-Dark for xfce too.

**Comment by Elbullazul** [comment]
can you be more specific about what changes you want?

**Comment by sidmint** [comment]
window manager theme that governs the title bar mostly and is contained in xfwm4 folder is not present.

**Comment by Elbullazul** [comment]
will look into it

**Comment by Elbullazul** [comment]
added with 5999c6c
