### ISSUE TITLE
fields in searchmonkey are invisible

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#11]
fields in searchmonkey are invisible until selected [once I even didn't know it existed until I found by accident clicking/guess].
Little better in Mint dark and Adwaita dark.

This theme
![2020-12-14-13:24:21](https://user-images.githubusercontent.com/43943312/102055001-34226400-3e10-11eb-8665-db68f68f4eb5.png)

mint dark
![2020-12-14-13:23:45](https://user-images.githubusercontent.com/43943312/102054982-2ec51980-3e10-11eb-8b16-dad264b56b6a.png)

adwaita dark
![2020-12-14-13:24:02](https://user-images.githubusercontent.com/43943312/102054991-3258a080-3e10-11eb-86a9-8bf13ba8cf87.png)

Linuxmint 19.3 xfce
Thank you, like the theme very much.

**Comment by Elbullazul** [comment]
69663e7 fixes this:
![image](https://user-images.githubusercontent.com/15310985/102085909-42a75600-3de5-11eb-816f-822e0fd18ac8.png)

**Comment by sidmint** [comment]
Thank you so much, still you can consider this: 

In my opinion, putting such a large area under that grey shade is not suitable for this black hole theme. Other themes can use different shades but this theme has to be limited regarding shades for preserving the absolute darkness. So I think just putting the grey shade to the boundaries of the fields would be better. And the two themes shown above have such a distinct border/boundary

**Comment by Elbullazul** [comment]
> that grey shade is not suitable for this black hole theme

Maybe a darker shade will be more suitable?
![image](https://user-images.githubusercontent.com/15310985/102788329-7566c680-4370-11eb-8e59-139a1cae7b44.png)

I'll commit the changes if you think it's better.

**Comment by sidmint** [comment]
thank you, darker shade is much better, go for it. And I think some shade is better than no shade to distinguish options area from the result area, unlike I wrote above.
