### ISSUE TITLE
can gtk3-style headerbar apps have zero margin too for title bar buttons?

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#12]
[so i found it's a gtk3 thing instead of Qt and edited the content]
Some apps like gnome-disk, archive manager[file-roller], gnome-calculator, evince [gnome-disk-utility shown below] have their own margins/offsets for the buttons [close button highlighted having an offset contrary to the theme] in title bar independent of the theme. Can't this be controlled by the theme?

![2020-12-21-20:27:46](https://user-images.githubusercontent.com/43943312/102790624-b809bc80-43cb-11eb-8c06-42763962cedc.png)

Mint 19.3 xfce

**Comment by Elbullazul** [comment]
hi, sorry for taking a bit too long to reply

although this is technically feasible, it requires playing with margins, and I'm not comfortable with that, as it has caused issues in the past. I also try not to mess up with GNOME's positioning of widgets to avoid having the buttons look out of place or break other controls.

If you don't mind the occasional bugs or weirdness, here's how to do it:

1. in `gtk-3.0/gtk.css` at line 1585, set `padding: 4px 8px` to `padding: 0;`
2. at line 1613, add `background-color: transparent;` to the `headerbar button` node
3. at line 1644 (now 1645), add the same snippet in the `headerbar button:backdrop` node

**Comment by sidmint** [comment]
Hiyee! Thanks a lot, also for also telling how to do it. 

> taking a bit too long to reply

oh don't say that, it's ok, it's life. Thank you for your help and works.
