### ISSUE TITLE
Just a curious question: how is gtk4 going to affect you and the team.

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#14]
I learnt that gtk4 is not that compatible with gtk3, if that's true then i guess you will have to do much hard-work again like in the past [gtk 3.20 isuue mentioned on site]. Would you like to share your thoughts? 
But i guess gtk4 will take its time to be adopted, like a couple of years, so you can relax for now?
Please throw some light on the future continuation of this theme and others when gtk4 arrives.
Thanks for all your work, I was just getting concerned.

**Comment by Elbullazul** [comment]
it's not that bad actually. There are some very noticeable differences in code, but a GTK 3 theme works mostly fine at the moment.

I think the migration will be a lot smoother this time, but we'll see. I want to keep supporting this project, but currently, it's hard for me to make time to work on it. I hope I'll find a way to work on this in the not-so-distant future.
