### ISSUE TITLE
path bar buttons is white in pcmanfm

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#2]
in pcmanfm, go to view>path bar and select 'buttons' instead of default 'location'. Its white and not matching.

![2020-10-23-18:28:17](https://user-images.githubusercontent.com/43943312/97006542-a9369300-155d-11eb-92ef-a1867e5e9d57.png)

**Comment by Elbullazul** [comment]
fixed:
![Xubuntu 20 04 beta-2020-10-25-12-56-14](https://user-images.githubusercontent.com/15310985/97113544-7c9b8c00-16c1-11eb-9be5-807c37a01a69.png)
