### ISSUE TITLE
gnome system monitor has an unmatching non-black colour band

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#4]
gnome system monitor has an unmatching non-black colour band in the above region where buttons [processes, resources, file systems] are present. Is it intended? I think it should be total black matching with the rest of the body.

![2020-10-26-07:19:06](https://user-images.githubusercontent.com/43943312/97126178-2c253c80-175c-11eb-878c-3fe0120a2114.png)

**Comment by Elbullazul** [comment]
what desktop environment are you using?

**Comment by sidmint** [comment]
I'm using xfce [mint 19.3 xfce]

**Comment by Elbullazul** [comment]
yeah, on gnome that's supposed to be the titlebar and it looks slightly transparent.

I'd have to see a way to have a black headerbar if not in gnome

**Comment by sidmint** [comment]
By the it looks fine and this way on:

![2020-10-28-05:13:53](https://user-images.githubusercontent.com/43943312/97373713-96fd8180-18dc-11eb-9f01-92d27ebb5d83.png)
1. Flat-Remix-GTK-Green-Darkest
and 

![2020-10-28-05:14:23](https://user-images.githubusercontent.com/43943312/97373731-9f55bc80-18dc-11eb-8f16-f5eff622853b.png)
2. Windows-10-Dark-3.2-dark

**Comment by Elbullazul** [comment]
89c32b6 addresses this
