### ISSUE TITLE
thick white border instead of usual hard-to-notice border

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#5]
Reproduce [shown in gif]: 
1 open gnome system monitor and select button other than 'processes' [that is 'resource' or 'file systems']
2 open another window, say a file manager
3 close newly opened window to shift focus to gnome system monitor automatically [as it's the recent most app]
4 processes button has this thick white border instead of usual hard-to-notice border usually in other themes.

Linuxmint 19.3 xfce.

![2020-10-26-07:37:18](https://user-images.githubusercontent.com/43943312/97127421-9095cb00-175f-11eb-8a5d-76de28994877.png)

![1](https://user-images.githubusercontent.com/43943312/97127672-4a8d3700-1760-11eb-8153-3765e9891e84.gif)

**Comment by Elbullazul** [comment]
that is intentional and in accordance with Microsoft's styling for focused buttons for Metro apps:
![image](https://user-images.githubusercontent.com/15310985/97321050-d6788f00-1844-11eb-9f04-3406a377cf45.png)

if you want to manually remove that styling, I can provide assistance

**Comment by sidmint** [comment]
Thank you for your active involvement. I'm so content using this theme, best I found till for me. 

Styling for focused buttons: Now I understood and find it okay and useful.

But I see some problems while switching it via tab button in gnome system monitor. Rectangle over 'processes' and 'resources' have only 3 white sides, next three selections are good as shown in gif, selection over the process named xfwm4 is not white at all [that may be intentional/exception for that type of area though, is that so?], and the last two selections of 'end process' and another icon [whose tool tip says 'show process properties'] has only one side as white as shown below.

![1](https://user-images.githubusercontent.com/43943312/97334777-1ff7c700-18a3-11eb-957a-f52866f1bc93.gif)

**Comment by Elbullazul** [comment]
It's caused by the way GTK draws controls. Basically, a child control can't be drawn outside of its parent's boundaries. But to have the intended effect, I had to offset by 2px, so it "fails" to draw some parts of the outline.

I had another look at what grouped buttons look like without the highlight:
![image](https://user-images.githubusercontent.com/15310985/97336790-c74e0d00-1855-11eb-8b92-6783375ef60f.png)

there should actually be spacing between button. I should rework the buttons, probably in a short time.

**Comment by Elbullazul** [comment]
> selection over the process named xfwm4 is not white at all [that may be intentional/exception for that type of area though, is that so?]

it is intentional. Only the buttons and text entries (if I remember correctly) are supposed to have that outline style

**Comment by Elbullazul** [comment]
c1fa436 corrects this issue

**Comment by sidmint** [comment]
Wow, thanks a lot, it's even more awesome now.
