### ISSUE TITLE
unable to see/scroll last line of package details in synaptic manager

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#7]
shown working fine in mint y dark and flat remix darkest.

![2](https://user-images.githubusercontent.com/43943312/98428033-b4dd9a00-20c5-11eb-8712-377c2ef80694.gif)

**Comment by Elbullazul** [comment]
on my side it works pretty well. Maybe if you restart the application?

**Comment by sidmint** [comment]
I used Linuxmint 19.3 xfce, this is an app [synaptic package manager] bug instead, I figured out by other cases and by moving the flexible bar for the package details area vertically [scroll bar doesn't get activated properly].
