### ISSUE TITLE
the horizontal scroll bar hides the bottom content in synaptic being a bit tall

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#8]
![2020-11-08-19:37:46](https://user-images.githubusercontent.com/43943312/98467212-1e5ec500-21fa-11eb-88b7-864753f2e4b3.png)

the name of the last package below libreoffice7.0-writer gets hidden due to the height of the horizontal scroll bar. It happens with Mint-y and flat-remix theme too but less as the height is less in those cases. So may be reducing the height may help.

Problem: when cursor reaches the last package, the package is hidden behind the scroll bar and very little margin is left above it to select the content.

**Comment by sidmint** [comment]
same for windows10 dark 3.2 theme version with the difference that initially the bar is thin and becomes thick when cursor actually reaches there.

**Comment by Elbullazul** [comment]
it's the way gnome handles scrollbars. Although I should probably add overlays back (the thin ones).

if you move the pointer away from the area, they disappear after a short while

**Comment by sidmint** [comment]
> if you move the pointer away from the area, they disappear after a short while

yes but problem is that when i want to click over it I can't do so easily as the bar appears over it instead.

> it's the way gnome handles scrollbars.

yeah and then nothing much can be done. Except making the bar bit thinner to increase the little available area to click [as in Mint-y and flat-remix theme], though that would be nit-picking still.

**Comment by Elbullazul** [comment]
okay, I'll add the overlay scrollbars back to this theme. Don't remember why I even removed them.

**Comment by sidmint** [comment]
> okay, I'll add the overlay scrollbars back to this theme. Don't remember why I even removed them.

but all themes I've seen till have the same issue, except that some have their bar a little [very little] thinner resulting in more remaining space, which doesn't make much difference anyway. 

So adding overlay scrollbars will be bringing a change for this issue which none else is doing? 

Will it affect many more places where this issue is not present and if yes then is that the right bargain?

**Comment by Elbullazul** [comment]
if you try the Windows 10 theme, you can see how it will look. Maybe synaptic doesn't even use overlay scrollbars, in which case I'll cancel the update and probably close the issue, as there's nothing I can do.

if it does change something, you will get a 2px-wide scroll indicator that expands to the full scrollbar when hovered over. It will probably still hide some content, but much less than currently

**Comment by sidmint** [comment]
just tried the Windows 10 theme on synaptic, glad to know it's indeed helpful. The scrollbar still hides the content but the difference is that it doesn't get activated until the I move pretty down, say second half of the last item's available space. Currently the scrollbars appear with any movement in the relevant area. So that will be helpful. And synaptic uses overlay scrollbars and you can proceed.
Just discovered that it's present in Mint theme already but I didn't realise until now!

Thank you. And I learnt something new that was dancing in front of my eyes!

**Comment by Elbullazul** [comment]
97f5f00 adds overlay scrollbars and should increase legibility

**Comment by sidmint** [comment]
[Thank you]s.
