### ISSUE TITLE
focus doesn't go away from top buttons of gnome system monitor

### ISSUE THREAD

**Issue by sidmint** [B00merang-Project/Windows-10-Mobile-Dark#9]
if gnome system monitor is opened and 'processes' is having the focus decoration [when it doesnt open with that tab active but the other two], then focus doesn't go away even after clicking the other two buttons [1st case]:
![0](https://user-images.githubusercontent.com/43943312/99151425-1bb01400-26c1-11eb-81a0-e42da604e4d0.gif)

I think that's not acc to intended design and it may be the fault of gnome system monitor handling and not this theme, but just to confirm I'm asking this.

That doesnt happen in this case below by the way where focus changes on clicking [2nd case]:
![1](https://user-images.githubusercontent.com/43943312/99151462-6893ea80-26c1-11eb-9dbd-e19cf46b158e.gif)

One more thing is that, in second case the decoration shifts to the button being clicked [can be seen above] but in the first case it goes away rather than shifting when clicked as shown below [3rd case]. This is another issue and may be again not the fault of the theme, just to confirm and I will create separate issue if confirmed:
![3](https://user-images.githubusercontent.com/43943312/99151642-a6ddd980-26c2-11eb-877b-f60c3ee3e583.gif)

linuxmint 19.3 xfce

**Comment by Elbullazul** [comment]
yes, I reproduced it. It seems there's inconsistency in the way gnome handles focus transfers. Did it happen with the previous version as well?

**Comment by sidmint** [comment]
latest 5.1 version is the first one I did install on my comp, so don't know about previous versions.

**Comment by Elbullazul** [comment]
but does it do the same thing on release 5.1, even with the broken outlines?

**Comment by sidmint** [comment]
yes, all the three cases are true for the 5.1 release with the broken outlines too.

**Comment by Elbullazul** [comment]
yeah, I think it's just the way GNOME handles focus now isn't what it uses to be.

> before: if a button is interacted with, it automatically becomes focused

> now: if a button is focused, it stays focused even if other buttons where used

or maybe focus always worked this way, but I didn't notice

Not much I can do, unfortunately
